[build]
  environment = { NODE_VERSION = "20" }
  command = "rm -rf node_modules package-lock.json && npm install --force && npm run build"
  publish = "dist"
  ignore_cache = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200