# Generated by Django 5.1.14 on 2026-05-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="venda",
            name="entregue",
            field=models.BooleanField(default=False),
        ),
    ]
