# Generated by Django 5.1.14 on 2026-05-01 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0002_venda_entregue"),
    ]

    operations = [
        migrations.RenameField(
            model_name="venda",
            old_name="Endereco_entrega",
            new_name="endereco_entrega",
        ),
    ]
