# Generated by Django 5.1.14 on 2026-05-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0004_cliente_senha"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="cpf_cnpj",
            field=models.CharField(
                blank=True, default="", max_length=18, verbose_name="CPF/CNPJ"
            ),
        ),
    ]
